version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/teamspeak-server
    steps:
      - checkout
      - run:
          name: Install AWS CLI and Deploy CloudFormation
          command: |
            sudo apt-get update && sudo apt-get install -qq -y python3-pip
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python3 get-pip.py
            pip3 install -q awscli --upgrade
      - run:
          name: Deploy to AWS
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            ./deploy.sh
workflows:
  version: 2
  deploy:
    jobs:
      - build